FROM ubuntu:14.04
MAINTAINER Cullen Jennings <fluffy@iii.ca>

RUN apt-get update 
RUN apt-get install -y git 
RUN apt-get install -y emacs24-nox


#EXPOSE 80,443

# the IP of the DB link gets put as a host in /etc/hosts with name db
#CMD ["./ks","db"]




