#%RAML 0.8

title: Fluffy Message Server API

documentation:
 - title: Overview
   content: |

       The message server takes messages that are signed with the integrity key
       for a given channel and adds them to that channel by allocating aa name
       for the in the CDN and pushing them into the CDN. The name is combination
       of the keyID and a sequence number that starts at 1 and increments by 1
       for each new post. The MS also tell the notification server to let all
       the users of this key know there is a new messages in the channel.


version: v1
baseUri: https://ms.fluffy.im/{version}
protocols: [ HTTP ]
mediaType: application/json

/ch/{keyID}:
    post:
      description: Create a new message for channel keyID and return a new sequence number for it  
      body:
      responses:
        200:
            body:
                application/json:
                    example: |
                         { "seqNum": "22" }


/ch/{keyID}/count:
    get:
        description: Get the last seqeunce number for that channel 


/msg/{keyID}-{seqNum}:
    get:
        description: Retrieve a specific message 
        
