#%RAML 0.8

title: Fluffy Message Server API

documentation:
 - title: Overview
   content: |

       The message server takes messages that are signed with the integrity key
       for a given channel and adds them to that channel by allocating a a name
       for the in the CDN and pushing them into the CDN. The MS also tell the
       notification server to let all the users of this key know there is a new
       messages in the channel.


version: v1
baseUri: https://ms.fluffy.im/{version}
protocols: [ HTTP ]
mediaType: application/json

/msg/{keyID}:
    post:
      description: Create a new message using keyID and return a new msgID for it  
      body:
      responses:
        200:
            body:
                application/json:
                    example: |
                         { "msgID": "3584784052509480386-22" }


/msg/{msgID}:
    get:
        description: Retrieve a specific message 
        
